stages:
  - build
  - push
  - deploy

.login-registry: &login-registry
  before_script:
    - docker login -u developer -p $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY 

variables:
  COMPOSE_INTERACTIVE_NO_CLI: 1
  BUILD_VERSION: $CI_BUILD_REF
  IMAGE_NAME: registry.pestelecom.ir/pioneer/frontend


build:
  stage: build
  tags:
    - docker
  only:
      - master
  variables:
    ENV_FILE: ".env"
  script:
    - cp "$ENV_FILE" .env
    - docker-compose build frontend

push-image:
  stage: push
  <<: *login-registry
  tags:
    - docker
  only:
    - master
  script:
    - docker-compose push frontend

push-latest:
  stage: push
  <<: *login-registry
  tags:
    - docker
  only:
    - master
  script:
    - docker-compose pull
    - docker tag $IMAGE_NAME:$BUILD_VERSION $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest


deploy:
  stage: deploy
  <<: *login-registry
  tags:
    - docker
  only:
    - master
  when: manual
  variables:
    ENV_FILE: ".env"
  script:
    - cp "$ENV_FILE" .env
    - docker-compose pull
    - docker-compose up -d frontend
    - docker image prune -af && docker image prune -af
